# Generated by Django 4.2.23 on 2025-09-02 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inmueble',
            name='imagen',
            field=models.ImageField(default='sin_imagen/', upload_to='inmuebles/'),
        ),
        migrations.AddField(
            model_name='perfiluser',
            name='imagen',
            field=models.ImageField(default='user_profile.jpeg/', upload_to='foto_perfil/'),
        ),
        migrations.AlterField(
            model_name='inmueble',
            name='precio_mensual',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
