# Generated by Django 4.2.24 on 2025-09-09 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_inmueble_imagen_perfiluser_imagen_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inmueble',
            name='imagen',
            field=models.ImageField(default='images/default.png', upload_to='inmuebles/'),
        ),
        migrations.AlterField(
            model_name='perfiluser',
            name='imagen',
            field=models.ImageField(default='images/user_profile.jpeg/', upload_to='foto_perfil/'),
        ),
    ]
