# Generated by Django 4.2.23 on 2025-08-28 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0004_perfiluser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfiluser',
            name='rut',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
    ]
